### ISSUE TITLE
Slack channel link on the HOWTO page is broken

### ISSUE THREAD

**Issue by sellicott** [sscs-ose/sscs-ose-chipathon.github.io#4]
The link to the ieee-sscs-dc-23 slack channel is broken on the HOWTO page. It presents a "No longer available" error when used. The current link is: https://join.slack.com/share/enQtNDc1MjgzMTc4NTYyMC03YTY5NjI0NGUxN2UyMjgzZmI5YTQyYTcxMzQxY2M4NjUyMTk3ODE3ZTgzNTY2ZmQ3M2Y0NjYyZDQ4NWZjYmQ5

**Comment by msaligane** [comment]
Thanks. The link is obsolete after 15 days. I will update it.

**Comment by msaligane** [comment]
Can you try this: https://join.slack.com/share/enQtNDkxOTIwNjQ5NzQxNC1kM2JkM2ViNTk5NmVhZTJmZGJjNDE4ODNiOTc3NTFhMDRiYjhmMDA4ZTYyZGQ5ZDgwMGNkNjFmMmQ0ZmQ5Yzg3

**Comment by sellicott** [comment]
Thanks
